### ISSUE TITLE
Extenson doesn't work with DevMode ON

### ISSUE THREAD

**Issue by daim2k5** [magento-hackathon/Lesti_Version#1]
Recoverable Error: Argument 1 passed to Varien_Data_Form_Element_Abstract::addElement() must be an instance of Varien_Data_Form_Element_Abstract, instance of Lesti_Version_Block_Adminhtml_Data_Form_Element_Version_Ajax given, called in /home/daim2k5/www/magento181.localhost/lib/Varien/Data/Form/Abstract.php on line 148 and defined  in /home/daim2k5/www/magento181.localhost/lib/Varien/Data/Form/Element/Abstract.php on line 55

**Comment by tobihille** [comment]
- Assigned to luemic scince i didn't found a simple way of fixing it

**Comment by stormbyte** [comment]
Fix pending in the Hackathon branch.
